version: '3.7'

services:
  web:
    build: .
    command: python /axpmda/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/axpmda
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:10
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: